title:   Kyle Reid
logo: "/images/Professional.Colour.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Kyle, a University of Guelph BBA Graduate/ aspiring Business Intelligence Analyst with a passion for combining business and data knowledge to solve problems. I love communicating insights through dashboards and helping businesses thrive!
  My education and work experiences helped mould me into the person I am today. Keep reading to learn more!
  <br><br>
  <a href="https://www.linkedin.com/in/kyle-reid-76bab0195/>View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/kyle.reid7667">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/Portfolio-Kyle-Reid-84a52a13470f492f9cbf23b2ca6fc79d">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal 
 
